# docker-compose up -d
# Use postgres/example user/password credentials
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 54320:5432
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./pgdata:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: 'azertyuiop'
      POSTGRES_DB: 'nestdb'
      POSTGRES_USER: 'postgres'
